### ISSUE TITLE
OG Image

### ISSUE THREAD

**Issue by chukwumaokere** [chronark/envshare#22]
I just realized when I shared this awesome product with a friend 
![image](https://user-images.githubusercontent.com/16673873/213424924-0b95822e-0f95-4362-aa28-b9af0e151fba.png)

It doesnt have an OG Image 

So I'm opening an issue to address this and crafting the OG Image endpoint using @vercel/og 

![image](https://user-images.githubusercontent.com/16673873/213425263-1b7f8584-4cca-4968-8603-39020d0d5376.png)

Mockup idea (not sold on the purple, there arent really "brand" colors for EnvShare so I'm just going with something that looks decent for now)

**Comment by chronark** [comment]
Yes, good point. I didn't have the time to add this before launching.

We could just use the hero section, wdyt?

Obviously with more padding
<img width="702" alt="image" src="https://user-images.githubusercontent.com/18246773/213428059-29019e55-b767-4b40-a196-5fdd6501ffff.png">

**Comment by chukwumaokere** [comment]
Let me cook that up and post it 

Also I opted to have this method with everything at the bottom saying "EnvShare" because you might want to use a different image on different pages so you can have something like https://envshare.dev/deploy show this OG Image
![image](https://user-images.githubusercontent.com/16673873/213429775-3c1ad74e-b167-445b-9516-5bc91785c116.png)

If you wanted. 

Here is the alternative 
![image](https://user-images.githubusercontent.com/16673873/213430273-90e785a2-ff34-458e-b641-a91a037881f4.png)


I keep "EnvShare" at the bottom for branding reasons but we can omit it if you prefer 
But also, if there is a favicon that we can use as a logo we decide on from the #18 issue, we can opt to put that at the bottom instead of the text "EnvShare"

**Comment by chronark** [comment]
Yeah good idea, I think you got this figured out more than I do :D

I'd probably go with the zinc gradient until we want to actually introduce a branding color

**Comment by chronark** [comment]
There'll be something like `/api/og?title=xxx&subtitle=xxx`, right?
and if subtitle is not defined it gets defaulted to the logo

or do you have a better idea?

**Comment by chukwumaokere** [comment]
Haha I've just been thinking about it a bit (branding/design and all)

You're right on the money!
i had it as `/api/v1/og` (though this endpoint doesnt need to be versioned because its for internal use and as it changes all respective implementations probably would change manually too!) 
I have a branch with this code and im just tightening it up for a PR

[here is the url for playing around with OG Image](https://og-playground.vercel.app/?share=dVJLbsIwEL2KNRs2sRKgLWqUsuMEVN1AF_k4ialjR86EJEXcveMEEKjtxp4ZPb2PPSdITSYghCiTR4bd26zju_kiCOr-k5V897JYuSpXoh8PnhrFJIqq4anQKCw7tA3KfLi2KHq81LP1XjN2Jd5DUvBExekXo6KwcSYJxdFwtCy3puLfUqf8NQj854DReGxX1C4D1vG8VYoMjZczsoeR_Z7_0eRoZNkT2pBMYlTG0JK61AVHWZQ4IcjIwJfBTeIh20Xv_4g3F-SjqWM9GRkBJKZpZAn3K7AbpErW3CHvws9v4buSjExKq_sMJLgtiZRt9FFaoytHHyXWX7OP2Mo4UaJhW5G2Vqgh8p2nvxxWyJ-IikhGtgdg5NOLTl93qaYbPDA1SqMbCE_QyQxLCN2qeFAK96AQ0rZ4kImkLSDMY9UID0RlDvJ9qN2OYTd2ROTybKpEZBCibcX5_AM)

**Comment by chronark** [comment]
adding a version never hurts, even if it's for internal stuff
